name: build (pull)

on:
  workflow_call:

jobs:
  build-warden-admission:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: warden/admission
      dockerfile: docker/admission/Dockerfile
  build-warden-operator:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: warden/operator
      dockerfile: docker/operator/Dockerfile
