name: build (push)
on:
  workflow_call:

jobs:
  compute-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get_tag.outputs.TAGS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the latest tag
        id: get_tag
        run: |
          {
            echo 'TAGS<<EOF'
            echo "${{ github.sha }}"
            echo "${{ github.ref_name}}"
            echo EOF
          } >> "$GITHUB_OUTPUT"
  build-warden-admission:
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: warden/admission
      dockerfile: docker/admission/Dockerfile
      tags: ${{ needs.compute-tags.outputs.tags }}
  build-warden-operator:
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: warden/operator
      dockerfile: docker/operator/Dockerfile
      tags: ${{ needs.compute-tags.outputs.tags }}
