name: integration tests (pull)

on:
  workflow_call:

jobs:
  integration-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rebase
      - uses: ./.github/actions/create-k3d-cluster
      - uses: ./.github/actions/setup-go
      - name: run test
        run: make verify-on-cluster
        env:
          IMG_DIRECTORY: dev
          IMG_VERSION: PR-${{ github.event.number }}
      - name: show warden logs
        if: failure()
        run: kubectl logs -l app=warden -n kyma-system --prefix=true;
