name: create release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name ( e.g. "2.1.3" )'
        default: ""
        required: true
        
permissions: # used by build images steps
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  verify-head-status:
    name: Verify HEAD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify github actions
        run: ./.github/scripts/verify-actions-status.sh ${{ github.ref_name }}

  upgrade-images:
    name: Upgrade main images
    needs: verify-head-status
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0
      
      - name: Bump sec-scanners-config.yaml
        run: ./.github/scripts/upgrade-sec-scanners-config.sh
        env:
          IMG_VERSION: ${{ github.event.inputs.name }}
      
      - name: Bump values.yaml
        run: |
          make replace-chart-images
        env:
          IMG_DIRECTORY: "prod"
          IMG_VERSION: ${{ github.event.inputs.name }}
      
      - name: Bump chart version
        run: ./.github/scripts/upgrade-chart-version.sh
        env:
          CHART_VERSION: ${{ github.event.inputs.name }}
      
      - name: Commit&Push
        run: |
          git config --local user.email "otter-releaser@otter-releaser.noreply.github.com"
          git config --local user.name "otter-releaser"

          git add .
          git commit --allow-empty -m "upgrade dependencies"
          git push origin ${{ github.ref_name }}

  create-tag:
    name: Create tag
    needs: upgrade-images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}  # Checkout to latest branch changes

      - name: Create tag
        run: |
          git tag ${{ github.event.inputs.name }}
          git push origin ${{ github.event.inputs.name }}

  compute-tags:
    needs: create-tag
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get_tag.outputs.TAGS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the latest tag
        id: get_tag
        run: |
          {
            echo 'TAGS<<EOF'
            echo "${{ github.sha }}"
            echo "${{ github.event.inputs.name }}"
            echo EOF
          } >> "$GITHUB_OUTPUT"

  builds:
    needs: create-tag
    uses: ./.github/workflows/_build.yaml

  create-draft:
    name: Create draft release
    needs: builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Create draft release
        id: create-draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_ID=$(./.github/scripts/release-draft.sh ${{ github.event.inputs.name }})
          echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT

      - name: Create release assets
        id: create-assets
        env:
          PULL_BASE_REF: ${{ github.event.inputs.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/release-assets.sh

      - name: Verify prow release jobs
        run: ./.github/scripts/verify-release-builds.sh ${{ github.ref_name }}

    outputs:
      release_id: ${{ steps.create-draft.outputs.release_id }}

  run-integration-test:
    name: Run integration test
    needs: create-draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-k3d-cluster
      - name: run test
        run: |
          make -C components/operator deploy
          make -C tests/operator test
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/dockerregistry-operator:${{ github.event.inputs.name }}
      - if: ${{ always() }}
        uses: ./.github/actions/collect-cluster-info

  publish-release:
    name: Publish release
    needs: [run-integration-test, create-draft]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.name }} 
          
      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/publish_release.sh ${{ needs.create-draft.outputs.release_id }}
