name: promote to release channel

on:
  workflow_dispatch:
    inputs:
      new_warden_tag:
        description: 'New warden tag (`x.x.x`)'
        default: ""
        required: true
      warden_skr_config_version:
        description: 'Warden SKR config version (`y.y`)'
        default: ""
        required: true
      channel:
        description: 'Module channel'
        default: "regular"
        required: true

env:
  MODULE_VERSION: ${{ github.event.inputs.new_warden_tag }}
  CHANNEL: ${{ github.event.inputs.channel }}
  # needed by gh cli for GitHub enterprise
 # GH_ENTERPRISE_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
 # WARDEN_SKR_OVERRIDES_REPO_URL: ${{ secrets.WARDEN_SKR_OVERRIDES_REPO_URL }}
  BOT_USERNAME: kyma-otter-serviceuser
  BOT_EMAIL: dl_545734d8fd84a02c39000002@global.corp.sap
 # GH_TOOLS_REPO_URL: ${{ secrets.GH_TOOLS_REPO_URL }}

jobs:

  create-tag:
    name: Create tag
    #needs: upgrade-images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }} # fetching the latest changes (incl. the commit from previous job) from branch name

      - name: Create lightweight tag
        run: |
          git tag ${{ github.event.inputs.new_warden_tag }}
          git push origin ${{ github.event.inputs.new_warden_tag }}

 #     - name: Verify job status
 #       run: ./.github/scripts/verify-release-builds.sh ${{ github.ref_name }}
