name: pull

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

jobs:
  unit-tests:
    uses: ./.github/workflows/_unit-tests.yaml

  gitleaks:
    uses: ./.github/workflows/_gitleaks.yaml

  builds:
    needs: [unit-tests, gitleaks]
    uses: ./.github/workflows/_build-pull.yaml

  integrations:
    needs: builds
    uses: ./.github/workflows/_integration-tests.yaml
    with:
      image: europe-docker.pkg.dev/kyma-project/dev/warden:PR-${{ github.event.number }}
