name: pull

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

jobs:
  unit-tests:
    uses: ./.github/workflows/_unit-tests.yaml

  gitleaks:
    uses: ./.github/workflows/_gitleaks.yaml

  builds:
    needs: [unit-tests, gitleaks]
    uses: ./.github/workflows/_build.yaml

  integrations:
    needs: builds
    uses: ./.github/workflows/_integration-tests.yaml
    with:
      directory-version: dev
      image-version: ${{ github.event.number }}
