name: pull

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  gitleaks:
    uses: ./.github/workflows/gitleaks.yaml

  builds:
    needs: [unit-tests, gitleaks]
    uses: ./.github/workflows/build-pull.yaml

  integrations:
    needs: builds
    uses: ./.github/workflows/integration-tests-pull.yaml
