name: push

on:
  push:
    branches: [ "main", "release-*" ]

jobs:
  builds:
    uses: ./.github/workflows/_build.yaml

  integrations:
    needs: builds
    uses: ./.github/workflows/_integration-tests.yaml

  upgrades:
    needs: builds
    uses: ./.github/workflows/upgrade-tests.yaml
